# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cs79rnlmx314rSqvACXFYM7UKg3BGSr2
"""

print("Hello World")